# Generated by Django 5.1.5 on 2025-02-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='почта/логин')),
                ('username', models.CharField(max_length=20, verbose_name='ник')),
                ('avatar', models.ImageField(default='avatars/unknown.png', upload_to='avatars/', verbose_name='изображение')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='описание')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('groups', models.ManyToManyField(blank=True, related_name='myuser_groups', related_query_name='myuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='myuser_permissions', related_query_name='myuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='титульник')),
                ('p_type', models.CharField(choices=[('game', 'Game'), ('life', 'Life')], default='life', max_length=6, verbose_name='категория')),
                ('text', models.CharField(max_length=1000, null=True, verbose_name='текст')),
                ('file', models.ImageField(default='img/unknown.png', upload_to='img/', verbose_name='пост')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.myuser', verbose_name='автор поста')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='камент')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.myuser', verbose_name='автор комента')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpost', to='main.publication', verbose_name='пост')),
            ],
        ),
    ]
